
//
//  HealthAlertsView.swift
//  LunaCare
//
//  Created by Fernanda Battig on 2025-11-07.
//

import SwiftUI

private extension Color {
    static let lcLavender      = Color(red: 0.74, green: 0.68, blue: 0.95)   // #BCAEF2
    static let lcLavenderSoft  = Color(red: 0.95, green: 0.95, blue: 0.98)   // ~#F7F7FB
    static let lcCardShadow    = Color.black.opacity(0.08)
    static let lcWarning       = Color(red: 0.93, green: 0.34, blue: 0.34)   // soft red
}



private struct HealthAlert: Identifiable {
    let id = UUID()
    let title: String
    let detail: String
    let confidence: Int         // 0…100
    let timestamp: String       // e.g., "Generated 2h ago"
}


struct HealthAlertsView: View {
    // Demo content — wire to your backend later
    @State private var alerts: [HealthAlert] = [
        .init(
            title: "Elevated stress pattern detected",
            detail: "Higher resting rate • Possible link to reduced sleep.",
            confidence: 92,
            timestamp: "Generated 2h ago"
        ),
        .init(
            title: "Mood fluctuation observed",
            detail: "Sadder than usual • Possible tie to reduced activity.",
            confidence: 88,
            timestamp: "Generated 4h ago"
        )
    ]

    var body: some View {
        ScrollView {
            VStack(spacing: 24) {

                // Header
                VStack(spacing: 8) {
                    Text("AI Health Alerts")
                        .font(.system(.title, design: .rounded).bold())
                        .shadow(color: .black.opacity(0.12), radius: 10, y: 6)

                    Text("Generated by your latest insights.")
                        .font(.system(size: 14))
                        .foregroundColor(.secondary)
                        .multilineTextAlignment(.center)
                }
                .padding(.top, 12)

                // Alert cards
                VStack(spacing: 14) {
                    ForEach(alerts) { alert in
                        AlertCard(alert: alert)
                    }

                    if alerts.isEmpty {
                        Text("No more alerts")
                            .font(.system(size: 13, weight: .semibold))
                            .foregroundColor(.secondary)
                            .padding(.top, 12)
                    }
                }

                Spacer(minLength: 8)
            }
            .padding(.horizontal, 24)
            .padding(.bottom, 24)
        }
        .navigationTitle("Health Alerts")
        .navigationBarTitleDisplayMode(.inline)
        .background(Color(.systemBackground))
    }
}



private struct AlertCard: View {
    let alert: HealthAlert

    var body: some View {
        RoundedRectangle(cornerRadius: 16, style: .continuous)
            .fill(Color.lcLavenderSoft)
            .shadow(color: .lcCardShadow, radius: 10, y: 6)
            .overlay(
                VStack(alignment: .leading, spacing: 10) {
                    HStack(alignment: .firstTextBaseline, spacing: 8) {
                        Image(systemName: "exclamationmark.triangle.fill")
                            .font(.system(size: 16, weight: .semibold))
                            .foregroundColor(.lcWarning)

                        Text(alert.title)
                            .font(.system(size: 16, weight: .semibold, design: .rounded))
                            .foregroundColor(.primary)

                        Spacer(minLength: 8)

                        // Confidence badge
                        Text("\(alert.confidence)%")
                            .font(.system(size: 12, weight: .semibold))
                            .foregroundColor(.primary)
                            .padding(.horizontal, 10)
                            .padding(.vertical, 5)
                            .background(Color.lcLavender.opacity(0.35))
                            .clipShape(Capsule())
                    }

                    Text(alert.detail)
                        .font(.system(size: 13))
                        .foregroundColor(.secondary)
                        .fixedSize(horizontal: false, vertical: true)

                    HStack(spacing: 6) {
                        Image(systemName: "clock")
                            .font(.system(size: 12))
                            .foregroundColor(.secondary)
                        Text(alert.timestamp)
                            .font(.system(size: 12))
                            .foregroundColor(.secondary)
                        Spacer()
                    }
                }
                .padding(16)
                .frame(maxWidth: .infinity, alignment: .leading)
            )
            .frame(maxWidth: .infinity, minHeight: 96)
            .accessibilityElement(children: .combine)
    }
}


#Preview {
    NavigationStack { HealthAlertsView() }
}
